### ISSUE TITLE
No such file or directory: jsc3d.console.js

### ISSUE THREAD

**Issue by markwal** [jneilliii/Octoprint-STLViewer#1]
**init**.py references several static files that aren't in the archive or the repo.  I think these are from the jsc3d library you mentioned.  Are you going to include them here or are they an external dependency?  For example jsc3d.console.js

IOError: [Errno 2] No such file or directory: '/home/pi/oprint/lib/python2.7/site-packages/octoprint_stlviewer/static/js/jsc3d.console.js'

**Comment by markwal** [comment]
But after I copied them over into your module in my site-libraries folder, tada bird!  Well, I renamed bird.stl to dragon.stl.  Pretty nifty.  :+1:

**Comment by jneilliii** [comment]
I'm new to python, git, pip and octoprint plugin development of course.  Any recommendations on getting these to load dynamically as part of the install it would be greatly appreciated.  I installed by cloning the git on the pi and running sudo python setup.py install.

**Comment by jneilliii** [comment]
I think I got it figured out.  Had to add the files to git and then push to the repo.  Should be fixed now, but still any recommendations are welcome.
