### ISSUE TITLE
Install Error on 1.3.0.post1+g1014712

### ISSUE THREAD

**Issue by stefanwendelmann** [jneilliii/Octoprint-STLViewer#18]
Octopi:
Version: 1.3.0.post1+g1014712 (master branch)

 pip install https://github.com/jneilliii/Octoprint-STLViewer/archive/master.zip

gives me:

Downloading/unpacking https://github.com/jneilliii/Octoprint-STLViewer/archive/master.zip
  Downloading from URL https://github.com/jneilliii/Octoprint-STLViewer/archive/master.zip
  Running setup.py (path:/tmp/pip-uKfvlq-build/setup.py) egg_info for package from https://github.com/jneilliii/Octoprint-STLViewer/archive/master.zip
    Could not import OctoPrint's setuptools, are you sure you are running that under the same python installation that OctoPrint is installed under?
    Complete output from command python setup.py egg_info:
    Could not import OctoPrint's setuptools, are you sure you are running that under the same python installation that OctoPrint is installed under?

----------------------------------------
Cleaning up...
Command python setup.py egg_info failed with error code 255 in /tmp/pip-uKfvlq-build
Exception information:
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/pip/basecommand.py", line 122, in main
    status = self.run(options, args)
  File "/usr/lib/python2.7/dist-packages/pip/commands/install.py", line 290, in run
    requirement_set.prepare_files(finder, force_root_egg_info=self.bundle, bundle=self.bundle)
  File "/usr/lib/python2.7/dist-packages/pip/req.py", line 1230, in prepare_files
    req_to_install.run_egg_info()
  File "/usr/lib/python2.7/dist-packages/pip/req.py", line 326, in run_egg_info
    command_desc='python setup.py egg_info')
  File "/usr/lib/python2.7/dist-packages/pip/util.py", line 716, in call_subprocess
    % (command_desc, proc.returncode, cwd))
InstallationError: Command python setup.py egg_info failed with error code 255 in /tmp/pip-uKfvlq-build

**Comment by jneilliii** [comment]
With OctoPi, you have to install either via the OctoPrint plugin manger or from command line you have to go into the OctoPrint/bin folder and use the command ~/oprint/bin/pip install https://github.com/jneilliii/Octoprint-STLViewer/archive/master.zip
