### ISSUE TITLE
Cannot load STL File from folder

### ISSUE THREAD

**Issue by jcastang** [jneilliii/Octoprint-STLViewer#20]
On OctoPrint 1.3.2, we cannot load STL file that are on folders.
We can only select folder on list view but there is no way to select file in this folder.

Thanks.

**Comment by jneilliii** [comment]
Thanks @jcastang I'll have to look into that as the folder support was added after my plugin was created.  Will have to dig into the api changes from foosel and see what needs to be updated to get full paths from the file list.  Not sure when I'll be able to get to that, but will put it on my to-do list.

**Comment by jneilliii** [comment]
So I found out someone else had already committed changes that supports folders.  The caveat is you have to go into the folder on the left hand file browser and then go to the stl viewer tab for it to update the list of files in that specific folder.
