### ISSUE TITLE
Broken in Octoprint Version 1.3.6

### ISSUE THREAD

**Issue by sameSEA** [jneilliii/Octoprint-STLViewer#23]
After update of Octoprint to Version 1.3.6 list of files in plugin screen is empty.

**Comment by jneilliii** [comment]
Can you upload your octoprint.log and check your browser's console for any errors on page load?  I don't use this plugin personally but just installed on my 1.3.6 octoprint and upload some stl files and the list is working fine for me in Chrome.

**Comment by sameSEA** [comment]
There are no related errors in browser log.
Octoprint log attached.
[octoprint (2).log](https://github.com/jneilliii/Octoprint-STLViewer/files/1586117/octoprint.2.log)

**Comment by jneilliii** [comment]
One thing I remembered.  Make sure your file list on the left isn't filtered for gcode files only.  When the stl files aren't in that list I don't think they show in the pull down on my plugin.

**Comment by sameSEA** [comment]
It worked. So filter on file list on the left is also filter for STL Viewer.

Thank you

**Comment by jneilliii** [comment]
Yes, that is correct.  Glad that was it.
