### ISSUE TITLE
Shows nothing

### ISSUE THREAD

**Issue by Tinchus2009** [jneilliii/Octoprint-STLViewer#25]
Hi, just installed, fresh nstall. latest octopprint installed, all octopi udated. I tried unistalling the plug in and reinstalling again. Nothing is shown  in the stl windows and also no file list is the dropdown box

![imagen](https://user-images.githubusercontent.com/14299602/42740770-228d8e5e-8882-11e8-8d94-b56800b505af.png)
 Btw: I use firefox

**Comment by jneilliii** [comment]
Did you try restarting octoprint and force a refresh by holding down ctrl + f5?

**Comment by Tinchus2009** [comment]
yes, octoprint rstarted and octopi restarted too

**Comment by jneilliii** [comment]
I'll have to test on my end with firefox, don't typically use that so not sure if it's related. What version of octoprint, installed on what os? Also, are there any errors in octoprint.log or the browser's console?

**Comment by Tinchus2009** [comment]
no error in octoprint, and in browser console, the ony that seems to be related is:
Connected to the server packed_core.js:12236:9
Finalizing application startup packed_core.js:14268:13
Going to bind 37 view models... packed_core.js:14152:13
Did not bind view model SoftwareUpdateViewModel to target #wizard_plugin_softwareupdate since it does not exist

Im on win 10 64b, octop 1.3.8
So I guess it doesnt work on firefox?

**Comment by jneilliii** [comment]
Not so.  Something else is going on here.  I just updated my Firefox install (was quite old) and went to my OctoPrint 1.3.9rc2 server and am not seeing any issues. Works as expected.  Quick question...this may seem odd, but is the file list filtered to only show gcode files and do you have stl files uploaded to your server (don't see any in your screenshot).

![image](https://user-images.githubusercontent.com/5249455/42742450-a1de6be6-8888-11e8-8c3a-504dc37a301e.png)

**Comment by Tinchus2009** [comment]
If you mean the file sorting un the octoprint interface, no, I have this:
![imagen](https://user-images.githubusercontent.com/14299602/42742720-92007a4c-8893-11e8-8332-c63f8791a564.png)

But, close this report... MY BAD, I though this plugin would let me see a model render from gcode file, not from a STL file
