### ISSUE TITLE
request:  view .gcode files

### ISSUE THREAD

**Issue by mark-hahn** [jneilliii/Octoprint-STLViewer#27]
I know this might be hard to impossible, but viewing .gcode files would be awesome.  A number of times I've wanted to see files I've uploaded to verify correct file to print.  But I don't do slicing in octo so I have nothing but gcode files.

**Comment by jneilliii** [comment]
Yeah, I've looked into possible integrations for this already and they are few and far between. The ones I did find didn't lend themselves to easy integration.

**Comment by jneilliii** [comment]
So I did a separate plugin that may work for you.  It adds a button on the gcode viewer tab to switch to 3d view.  You can install manually using the following url in plugin manager.

https://github.com/jneilliii/OctoPrint-GCode3D

**Comment by jneilliii** [comment]
So there is a far better gcode viewer available so closing this ticket, referencing that plugin.

https://github.com/Kragrathea/OctoPrint-PrettyGCode
