### ISSUE TITLE
OctoPrint 1.3.11 No longer accepts STL?

### ISSUE THREAD

**Issue by DylanCDuke** [jneilliii/Octoprint-STLViewer#28]
I could be wrong here - but recently updated to 1.3.11 - looks like every time I try to upload an stl it requires a .g, .gcode, or .gco format? Any ideas why this may be?

**Comment by jneilliii** [comment]
There's a chance with the removal of the bundled cura plugin the files aren't recognized for upload. Maybe installing the cura plugin back might resolve the issue.

**Comment by DylanCDuke** [comment]
@jneilliii currently in a print - will give this a try after and let you know

**Comment by DylanCDuke** [comment]
Yep - this worked no problem @jneilliii - thank you
