### ISSUE TITLE
No files in the file dropdown 

### ISSUE THREAD

**Issue by msteele999** [jneilliii/Octoprint-STLViewer#31]
OctoPrint 1.4.0, Windows Home 10

I installed the plugin but when I select the tab, the file dropdown contains no entries.

Please let me know if you would like my logs or if there is any other information I need to provide.

Best regards,

Mark

**Comment by jneilliii** [comment]
Can you show me a screenshot of your filelist with STL files and check if forcing a refresh of your browser has any effect?

**Comment by msteele999** [comment]
Here you go - FYI - this is OctoPrint 1.4.0 running on Windows 10

[image: Screenshot_052720_063407_AM.jpg]

***
*Mark Steele*
CIO / VP Technical Operations | TelVue Corporation
TelVue - We Share Your Vision
16000 Horizon Way, Suite 100 | Mt. Laurel, NJ 08054
800.885.8886 | msteele@telvue.com | http://www.telvue.com
twitter: http://twitter.com/telvue | facebook:
https://www.facebook.com/telvue

**Comment by jneilliii** [comment]
Sorry but screenshots don't come through on email replies... also, just to confirm. You're running octoprint on windows 10 or are you accessing octoprint from a windows 10 computer?

**Comment by msteele999** [comment]
I am running OctoPrint on Windows 10. I access the dashboard thru the web
gui on another computer. I can send the screen shot to another email
address if you like or I can go to git and put it there.

***
*Mark Steele*
CIO / VP Technical Operations | TelVue Corporation
TelVue - We Share Your Vision
16000 Horizon Way, Suite 100 | Mt. Laurel, NJ 08054
800.885.8886 | msteele@telvue.com | http://www.telvue.com
twitter: http://twitter.com/telvue | facebook:
https://www.facebook.com/telvue

**Comment by msteele999** [comment]
![unnamed](https://user-images.githubusercontent.com/6474337/83023430-e6244b00-9ffa-11ea-818b-bccee4dc7ae0.jpg)

**Comment by jneilliii** [comment]
So I don't see any STL files in that file list on the left @msteele999. This plugin doesn't render gcode files...You may be looking for PrettyGcode plugin? To install that you can use the URL below in plugin manager as it's not officially published on the plugin repository if I'm remembering correctly.

https://github.com/Kragrathea/OctoPrint-PrettyGCode/archive/master.zip

**Comment by msteele999** [comment]
LOL - oh man - I'm sorry dude - I did not realize that I did not load STL
files - I feel foolish.

***
*Mark Steele*
CIO / VP Technical Operations | TelVue Corporation
TelVue - We Share Your Vision
16000 Horizon Way, Suite 100 | Mt. Laurel, NJ 08054
800.885.8886 | msteele@telvue.com | http://www.telvue.com
twitter: http://twitter.com/telvue | facebook:
https://www.facebook.com/telvue
