### ISSUE TITLE
Does not show file list

### ISSUE THREAD

**Issue by Vantiveman** [jneilliii/Octoprint-STLViewer#37]
Does this only work with files copied onto the SD card?
I have files loaded in Octoprint but I don't see these displayed by the plug-in.

**Comment by jneilliii** [comment]
the plugin only displays stl files that are uploaded to OctoPrint local.

**Comment by Vantiveman** [comment]
I’m not sure what you mean by Octoprint local.

I have mapped the octoprint file location as a drive on my Win10 system and save from the slicer directly to Octoprint. I see all these files in the file list in the octorpint GUI.

**Comment by jneilliii** [comment]
> save from the slicer directly to Octoprint

this means you are saving gcode files, not stl files.

**Comment by jneilliii** [comment]
Maybe you are looking for something like my [slicer thumbnails](https://plugins.octoprint.org/plugins/prusaslicerthumbnails/) plugin?

**Comment by Vantiveman** [comment]
Ah, of course. Obviously it would require the STL file. Don’t know where my head was!

Many thanks.
