### ISSUE TITLE
No files in dropdown menu

### ISSUE THREAD

**Issue by fiaskogaul** [jneilliii/Octoprint-STLViewer#38]
Hi,

I don't get any files in the dropdown menu on both of my printers (each with its own RasPi). I think I also know the reason and it might be an intended behavior. But maybe you can help me:

I normally slice my files in Cura and upload them directly from cura via the "OctoPrint Connection" plugin to OctoPrint which also triggers the print to start.

I assume that Cura stores the files directly in /.octoprint/uploads without the detour through the /.octoprint/watched folder. If I understand correctly STLViewer only recognizes files when they went through the watched folder.

Am I right and do you know a workaround how to make STLViewer see the files?

Thanks an regards

**Comment by jneilliii** [comment]
Stl viewer only will show stl files, not sliced  gcode. You're probably looking for one of my thumbnail plugins or pretty gcode.

**Comment by fiaskogaul** [comment]
@jneilliii yeah that makes sense now... Thanks a lot! I will look into them.
