### ISSUE TITLE
Can't load stl

### ISSUE THREAD

**Issue by fabiovogt** [jneilliii/Octoprint-STLViewer#39]
I installed the plugin but unfortunately I can't select a stl file. I had some stl's saved on my octo install but also when I upload a new one I can't load it, there is only the "choose..." prompt. 

<img width="1440" alt="Bildschirmfoto 2021-12-30 um 12 50 57" src="https://user-images.githubusercontent.com/29067236/147749540-85811f99-0d6f-4e14-8280-200fc920adb7.png">

**My setup:**
OctoPrint 1.7.2 
Python 3.7.3 
OctoPi 0.18.0

Google Chrome Version 96.0.4664.110

**Comment by jneilliii** [comment]
The plugin only works for upload stl files, not gcode files. You are probably looking for either my thumbnail plugin or pretty gcode plugin.

**Comment by fabiovogt** [comment]
D'oh! Your are completely right! Sorry for disturbing you :)
